name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y graphviz doxygen

      - name: Build documentation
        run: make doxygen

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/html
          ssh-key: ${{ secrets.DEPLOY_KEY }}
