name: Testing clang format
on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run clang-format
        run: |
          make .clang-format
          clang-format --dry-run --Werror --style=file ./include/*.hpp
