name: Doxygen GitHub Pages Deploy Action

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get install -y graphviz doxygen plantuml curl default-jre default-jdk
          pip install -r ./requirements.txt
          curl -Lo plantuml.jar "https://github.com/plantuml/plantuml/releases/download/v1.2023.4/plantuml.jar"

      - name: Build uml
        run: make uml EXTRA_PARAMS_PLANTUML="java -jar ./plantuml.jar"

      - name: Build documentation
        run: make doxygen
